version: "3.9"
services:
    web:
        build:
            context: ./repo
            dockerfile: ./repo/Dockerfile
        networks:
            - backend

    db:
        image: mariadb
        restart: always
        # command: --default-authentication-plugin=mysql_native_password
        # volumes:
        #   - ~/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: db-name
            MYSQL_ROOT_PASSWORD: 12345678
        networks:
            - backend

    adminer:
        image: adminer
        ports:
            - 8081:8080
        networks:
            - backend
networks:
    backend:
        driver: bridge
