version: "3.9"
services:
    db:
        image: mariadb
        restart: always
        # command: --default-authentication-plugin=mysql_native_password
        # volumes:
        #   - ~/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: db-name
            MYSQL_ROOT_PASSWORD: 12345678

    adminer:
        image: adminer
        ports:
            - 8081:8080
