version: "3.9"
services:
    adminer:
        image: adminer
        ports:
            - 85:8080
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
    laravel:
        build:
            context: ./example-app
            dockerfile: ./Dockerfile
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_USERNAME=root
            - DB_DATABASE=12345678
            - APP_DEBUG=true
        command:
            - php artisan key:generate
            - entrypoint.sh
        ports:
            - 86:8000
